name: Terraform Version Check

on:
  workflow_dispatch:  # manual trigger
  pull_request:
    branches:
      - prod          # run on PRs to prod branch
  push:
    branches:
      - prod          # run on pushes to main branch


jobs:
  check-tf-version:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.3
      - run: terraform init -backend-config=incode.tfbackend --reconfigure

